version: "3"

services:
  mysql:
    image: "mysql:8.1"
    container_name: "java-mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: database
  app:
    build: ./
    container_name: "java-app"
    ports:
    - 8080:8080