version: "3"

services:
  postgres:
    image: "postgres:latest"
    container_name: "database"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"

  backend:
    build: ./
    container_name: "backend"
    ports:
      - "8080:8080"