version: "3"

services:
  mysql:
    image: "mysql:8.1"
    container_name: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: database
  app:
    build: ./
    container_name: "backend"
    ports:
      - "8080:8080"